name: Create Release on Tag Push

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

# https://github.com/marketplace/actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clone origin and apply patches
        run: |
          # mkdir -p ${{ github.workspace }}/go
    
          git clone https://github.com/IAliceBobI/sy-tomato-plugin.git ./origin
          cd origin
          git apply --ignore-whitespace ${{ github.workspace }}/patches/user.patch
          git apply --ignore-whitespace ${{ github.workspace }}/patches/IndexConf.patch
    
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/origin/
          npm i
          npm run build
          
      - name: make zip package
        run: |
          cd build
          zip -r package.zip ./*
          mv package.zip ..

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "package.zip"
          prerelease: false

